### ISSUE TITLE
디버깅

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/shop-ssgnack#10]
## 디버깅
 구현한 기능들을 합치고 정상적으로 작동하는지 확인합니다.

## TODO
- [ ] 기능 정상 작동 확인
- [ ] 오류 발생 처리 확인
- [ ] 예외 처리 확인

## 최종결과
- [ ] 디버깅 완료
