### ISSUE TITLE
입출고, 재고 처리 UI 구현

### ISSUE THREAD

**Issue by dmlwls12** [ssg-240304-java2/shop-ssgnack#15]
## 입출고, 재고 처리
프론트 화면을 구현합니다

## TODO
- [x] 입출고, 재고 처리 화면 구현
- [x] 기능 카테고리 버튼 구현

## 최종결과
- [x] 기능 구현 완료
