### ISSUE TITLE
입출고, 재고 관리 UI 수정

### ISSUE THREAD

**Issue by dmlwls12** [ssg-240304-java2/shop-ssgnack#16]
## 재고관리
 재고를 조회합니다.

## TODO
- [x] 입출고, 재고 조회 화면 구성
- [x] 입출고, 재고 검색 화면 구성

## 최종결과
- [x] 기능 구현 완료
