### ISSUE TITLE
재고관리 기능 개발

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/shop-ssgnack#4]
## 재고관리
 재고를 조회합니다.

## TODO
- [ ] 재고 조회 기능 개발
- [ ] 재고 검색 기능 개발

## 최종결과
- [ ] 기능 구현 완료
