### ISSUE TITLE
매출 보고 및 분석

### ISSUE THREAD

**Issue by Gyunorld** [ssg-240304-java2/shop-ssgnack#7]
## 매출 보고 및 분석
 매출을 그래프를 통해서 확인하고 분석합니다.

## TODO
- [x] 전체 매출 조회
- [x] 제품별 매출 조회
- [x] 브랜드별 매출 조회
- [x] #25 

## 최종결과
- [x] 기능 구현 완료
